name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build & Test (${{ matrix.os }} / Java ${{ matrix.java }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [17, 21]
        exclude:
          - os: windows-latest
            java: 21     # excluded combo
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build and run tests with Maven
        run: mvn -B clean verify

      - name: Upload Surefire test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ matrix.os }}-java${{ matrix.java }}
          path: target/surefire-reports/*.xml

      - name: Upload JaCoCo coverage report (XML)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-java${{ matrix.java }}
          path: target/site/jacoco/jacoco.xml

      - name: Build Docker images
        run: docker build -t myapp:ci .

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo bash
        
      - name: Scan Docker image with Grype
        run: |
          grype myapp:ci -o json > grype-report.json
      - name: Upload Grype JSON report
        uses: actions/upload-artifact@v4
        with:
          name: grype-report
          path: grype-report.json




  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main'   # only on main commits
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Download JaCoCo report from matrix
        uses: actions/download-artifact@v4
        with:
          name: coverage-ubuntu-latest-java21 
          path: target/site/jacoco

      - name: Build for analysis
        run: mvn -B clean verify -DskipTests

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=zahnfee64_ci-cd-uebung-Rechberger -Dsonar.organization=zahnfee64 -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

